package com.ratioapp.routes

enum class NameScreen {
    HOME, DETAIL_PHOTO_ME,DETAIL_PHOTO_USER,
    PROFILE_ME, PROFILE_USER,
    WALLET, DONATE_AMOUNT,
    LOGIN,
    REGISTRATION, DETAIL_ALBUMS, WITHDRAWAL,
    MIDTRANS_PAYMENT, CHAT, DETAIL_CHAT,
    FORM_CREATE_PHOTO,
    EDIT_PROFILE, DETAIL_FOLLOW, PIN,
    STATUS_MIDTRANS
}

enum class TypeFollow {
    FOLLOWING, FOLLOWERS
}